os: linux
dist: bionic
language: minimal

# prevent branch builds that aren't PRs
branches:
  only:
    - master

env:
  global:
    - BUILD_NAME=FiscalShock

after_failure:
  - bash ./ci/discord_hook.sh failure ${WEBHOOK_URL}

cache:
  directories:
    - .git/lfs
    - fiscal-shock/Library

git:
  depth: 25  # warning: tags more than this many commits ago will be lost!
  lfs_skip_smudge: true

stages:
  - test
  - cache
  - build
  - docs
  - deploy

################################################################################

jobs:
  include:
  - stage: test
    name: "Tests"
    if: type == pull_request
    services:
      - docker
    script:
      - source ./ci/travis_prepare_workspace.sh
      - bash ./ci/travis_run_tests.sh
      - echo Testing Linux build
      - bash ./ci/docker_build.sh
    env: IMAGE_NAME=gableroux/unity3d:2019.3.0f6 BUILD_TARGET=StandaloneLinux64 OPTS=-force-glcore BUILD_DIR=FiscalShock-linux64

################################################################################

  - stage: cache
  ############################
  # Clone once (includes LFS)
  ############################
    name: "Clone repository and LFS"
    script:
      - bash ./ci/lfs_pull.sh
    if: type != pull_request
    workspaces:
      create:
        name: lfs
        paths:
          - .

  - stage: build
  ############
  # Linux 64
  ############
    name: "Build and cache Linux64 (OpenGL)"
    script:
      - export IMAGE_NAME=gableroux/unity3d:2019.3.0f6; export BUILD_TARGET=StandaloneLinux64; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-linux64
      - cd dmr-capstone/dmr-capstone
      - source ./ci/travis_prepare_workspace.sh
      - bash ./ci/docker_build.sh
      - bash ./ci/package_build.sh linux64
    if: type != pull_request
    services:
      - docker
    git:
      clone: false
    workspaces:
      use:
        - lfs
      create:
        name: linux64
        paths:
          - rls_linux64

  ############
  # Windows 64
  ############
  - script:
      - export IMAGE_NAME=gableroux/unity3d:2019.3.0f6-windows; export BUILD_TARGET=StandaloneWindows64; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-win64
      - cd dmr-capstone/dmr-capstone
      - source ./ci/travis_prepare_workspace.sh
      - bash ./ci/docker_build.sh
      - bash ./ci/package_build.sh win64
    name: "Build and cache Windows64 (OpenGL)"
    if: type != pull_request
    services:
      - docker
    git:
      clone: false
    workspaces:
      use:
        - lfs
      create:
        name: win64
        paths:
          - rls_win64

  ############
  # mac
  ############
  - script:
      - export BUILD_TARGET=StandaloneOSX; export IMAGE_NAME=gableroux/unity3d:2019.3.0f6-mac; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-mac
      - cd dmr-capstone/dmr-capstone
      - source ./ci/travis_prepare_workspace.sh
      - bash ./ci/docker_build.sh
      - bash ./ci/package_build.sh mac
    name: "Build and cache macOS (OpenGL)"
    if: type != pull_request
    services:
      - docker
    git:
      clone: false
    workspaces:
      use:
        - lfs
      create:
        name: mac
        paths:
          - rls_mac

################################################################################

  - stage: docs
    name: "Doxygen"
    script:
      - cd dmr-capstone/dmr-capstone
      - bash ./ci/generate_docs.sh
    if: type != pull_request
    language: python
    python:
      - "3.8"
    addons:
      apt:
        packages:
          - doxygen
    git:
      clone: false
    workspaces:
      use:
        - lfs
    deploy:
      provider: pages:git
      token: $GITHUB_TOKEN
      edge: true
      commit_message: Update Doxygen %{git_sha}
      verbose: true
      project_name: Fiscal Shock
      local_dir: docs/html
      skip_cleanup: true
      name: "Deploy Moar RAM"
      email: "52723879+travis-pantry-raid@users.noreply.github.com"
      on:
        branch: master

################################################################################

  - stage: deploy
    name: Publish release to GitHub
    script:
      - cd dmr-capstone/dmr-capstone
      - ls -la *
      - source ./ci/verify_package.sh linux64 || travis_terminate 1
      - source ./ci/verify_package.sh win64 || travis_terminate 1
      - source ./ci/verify_package.sh mac || travis_terminate 1
      - bash ./ci/travis_set_tag.sh || travis_terminate 1
    if: type != pull_request
    git:
      clone: false
    workspaces:
      use:
        - lfs
        - linux64
        - win64
        - mac
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      name: "Fiscal Shock auto release ${git_sha}"
      body: "These releases were built automatically for OpenGL from commit %{git_sha}."
      overwrite: true
      prerelease: true
      file:
        - rls_linux64/FiscalShock-linux64.tar.gz
        - rls_win64/FiscalShock-win64.zip
        - rls_mac/FiscalShock-mac.tar.gz
